### ISSUE TITLE
how to control the duration of a transition?

### ISSUE THREAD

**Issue by capaj** [maisano/react-router-transition#10]
there is no informartion on how to control the duration of a transition animation.

**Comment by jacobangel** [comment]
This is because the underlying library behind the animation, [React Motion](https://github.com/chenglou/react-motion#faq), does not allow duration to be specified. They do a great job explaining this decision, and how to work with it in their [Spring Parameter Choosing Documentation](http://chenglou.github.io/react-motion/demos/demo5-spring-parameters-chooser).

**Comment by capaj** [comment]
Yeah I noticed that just a minute ago. Very interesting approach. So in order to make the animation longer,  I can adjust stiffness and dampen params right?

**Comment by jacobangel** [comment]
That is correct.

**Comment by maisano** [comment]
@capaj the [presets](https://github.com/maisano/react-router-transition/blob/master/src/presets.js) have some examples of passing in spring configs.
