### ISSUE TITLE
Attempted import error: 'useLocation' is not exported from 'react-router-dom'

### ISSUE THREAD

**Issue by internationalhouseofdonald** [maisano/react-router-transition#113]
So, I tried to get the Animated Switch working, but I got this error message. I did some research and found out that useLocation is exported from react-router, but not react-router-dom. I switched the `rrt` package to import from react-router instead and I got a Route that was positioned absolutely so that everything that is supposed to be beneath it was behind it.

Basically, my footer was up where it says "Projects"
![image](https://user-images.githubusercontent.com/20768148/68536238-4086e400-0315-11ea-8995-a98c05b69841.png)

**Comment by SaniJasi** [comment]
Please update react-router-dom for the latest version!

**Comment by pfloresl** [comment]
same issue here.

**Comment by maisano** [comment]
`react-router-dom` is a peer dependency, with a minimum major of 5. In order to use this package, as @SaniJasi suggests, upgrade the version of `react-router-dom` that you're using to at least 5.

@internationalhouseofdonald if you want to transition your entire content section (and need to use absolute positioning), this is more of a layout concern. You might endeavor to use a sticky footer, or provide a minimum content height, though it really depends on the intent of your design + the desired transition.

**Comment by pfloresl** [comment]
using react-router-dom react-router-dom@5.1.2",

**Comment by maisano** [comment]
@pfloresl which version of `react-router` do you have installed? Do you have both of these packages installed, or are you relying on `react-router` as a transitive dependency. I ask because you might have both discretely installed, and at different versions–[`react-router-dom` proxies all exports from `react-router`](https://github.com/ReactTraining/react-router/blob/b08a9352a22086d529be09aa7fb5787dd0f02c79/packages/react-router-dom/modules/index.js#L1-L16).

**Comment by pfloresl** [comment]
no, react-router , i have "react-dom": "^16.12.0",
    "react-router-dom": "^5.1.2",
    "react-router-transition": "^2.0.0","react": "^16.12.0",

**Comment by josh231101** [comment]
This is not working. Someone please help

**Comment by josh231101** [comment]
**Simple solution inside your parent component that renders the route**

`useEffect(() => {
        window.scrollTo(0, 0);
    }, [])`
