### ISSUE TITLE
changing urls manually breaks

### ISSUE THREAD

**Issue by beckend** [maisano/react-router-transition#12]
So i tried to change URL manually using [guide](https://github.com/reactjs/react-router/blob/master/docs/guides/NavigatingOutsideOfComponents.md).

1. When application starts, route matches component `App`. A nice opacity transition is done.
2. `App` immediately at `componentWillMount` changes URL.
3. Result: a duplicate DIV is made, there are now 2 `App` components in DOM.

**Comment by maisano** [comment]
in order to address this issue, i think i need some more information. i've done my best to enumerate some questions that would hopefully give me enough information to help:

1. why are you re-routing in the `componentWillMount` of `<App />`?
2. what do your route declarations look like?
3. what does the `render` body of `<App />` look like?

**Comment by beckend** [comment]
The route match for app is:
```javascript
<Route path='/app*' component={ require('./components/app/app') }>
```
I have an Iframe inside app, so I change the URL to reflect the iFrame sub pages:
`http://app.dev/page/sub-page`.

So if you login into the application from route `/login`, you are redirected to `/app`.
App async loads iFrame, when it's loaded, the URL is updated to reflect what page the iFrame is on.

This is done because the user can visit the site with path such as `/app/page/my-page'.

I noticed that `react-router-transition` will try to transition when I do these URL manipulations and causing the issue. The thing is I never leave my route, since it's `/app*`.

**Comment by maisano** [comment]
thanks for the details.

the `pathname` prop of `RouteTransition` is essentially a key mapping to the matched route. i hadn't considered fuzzy paths when designing it. the problem is that `RouteTransition` thinks you're trying to render a wholly different component and will apply the transition accordingly. as a fix in the interim, it should be easy enough to not use the fully-qualified path in this instance, and to just pass in `'/app'` for the pathname when you're within the app tree.

**Comment by beckend** [comment]
I see, i did a monkey patch, passing a monkey function to location prop worked nicely.

**Comment by maisano** [comment]
awesome. if you have any ideas/opinions on how this should be handled within `RouteTransitions`, feel free to open a pr :)
