### ISSUE TITLE
Lag while transitioning?

### ISSUE THREAD

**Issue by saadq** [maisano/react-router-transition#17]
There seems to be a delay between the opacity change and the element fixing its size. Here is a quick vid:

![animation](https://cloud.githubusercontent.com/assets/5678694/17804235/78487d56-65af-11e6-9839-415bd0933654.gif)

As you can see, there is a slight delay after I have changed tabs and the size of the content readjusting. Is this intentional, or is this an issue?

Here is what I have on my `RouteTransition`:

```javascript
<RouteTransition
  pathname={this.props.location.pathname}
  atEnter={{ opacity: 0 }}
  atLeave={{ opacity: 0 }}
  atActive={{ opacity: 1 }}
>
  {this.props.children}
</RouteTransition>
```

**Comment by maisano** [comment]
@saadq–this looks like an issue of not using `position: absolute` for your routes. `RouteTransition` works by applying styles to your components on mount and unmount (via `atEnter` and `atLeave`)–what it looks like in your case is that the children are being faded out entirely before being removed. unfortunately the library only works when routes are positioned absolutely.

you can fix this by applying that style to your routes, though it should also be fixed in the library. feel free to submit a pr :)

**Comment by saadq** [comment]
Sorry, missed that in the docs. Thanks for the quick reply.
