### ISSUE TITLE
Adding delays to animations

### ISSUE THREAD

**Issue by stephendandrea** [maisano/react-router-transition#36]
Loving this library. 

Wondering if there was a simple way to add delays to animations. 
Say for instance you have multiple components that you want to animate in one after another or at specified times.

Might be something simple but I don't see it anywhere in the code.
high level looking to do something like this: 
```javascript 
atEnter={{ 
  'opacity' : '0',
  'animation-delay' : '250ms',
  '-webkit-animation-delay' : '200ms'
}}
``` 

or perhaps is there a way to add a custom class to the element that handles the transition?

**Comment by maisano** [comment]
thanks for the kind words @stephendandrea!

this library is a thin layer on top of [react-motion](https://github.com/chenglou/react-motion)'s `TransitionMotion` component. the animations that react-motion supports are not time-based, but instead spring-based. because of this, delays and durations are not supported. you _can_ control the spring configuration (stiffness & damping) but i don't believe the effect you want is achievable through this.

that said, you _might_ be able to get what you're looking for if you use `StaggeredMotion` with some magic to interleave mounting/unmounting routes. i'm not super familiar with the limitations of that component, but it's worth investigating if you want routes to animate in some staggered/cascading fashion.

**Comment by maisano** [comment]
@stephendandrea closing this issue as we don't currently support this, but feel free to reach out with any other questions/ideas :)

**Comment by rumanbsl** [comment]
A code snippet with spring-based animation would be nice.
