### ISSUE TITLE
Using `location.key` instead of `location.pathname`

### ISSUE THREAD

**Issue by kompot** [maisano/react-router-transition#48]
When using currently suggested `location.pathname` and navigating back and forth between URLs that are currently in use then there's a weird animation overlap. Replacing it with `location.key` does exactly what it should - correctly identifies routes, and not depending on current pathname.

So the proposal is to alter readme to make `location.key` the default and maybe rename prop from `pathname` to `key` to reflect the real meaning.

This should resolve
https://github.com/maisano/react-router-transition/issues/21

**Comment by maisano** [comment]
@kompot this is an expected behavior–react-motion is _interruptible_ by design. if you toggle between two routes and we treat `location.pathname` as the key, the transition will be interrupted and resolve using the latest state. as you mentioned, this differs when we use `location.key` as the source of truth as each key entry is unique and routes will be treated as new entities on each location change.

the reasoning behind `location.pathname` being selected over `location.key` is twofold:

1. the key will change on location changes. this means that if the transition exists at the root level (`/home`, `/about`, etc.), and the user navigates within a subroute (`/about/team` => `/about/location`) the entire tree at the root level will retransition. tying it to the pathname, or a section of the pathname (e.g. the first segment of the pathname) will prevent this.
2. if you have two separate `RouteTransition` components coexisting, navigations would change them both–this is most likely not desired.

that said, the readme could, and should, explain this a bit more thoroughly. thankfully i'm planning on changing some stuff around in the near future and exposing some components specific to the react-router v4 api (`AnimatedSwitch` & `AnimatedRoute`) where folks won't have to think about this prop or how it works.

**Comment by kompot** [comment]
Well, ok, looking forward to the stuff changed.

I really thought that was a unexpected behaviour. In my case it is and I will stick with `location.key` for now.

Closing this as I see that there's much more to the issue than my use case.
