### ISSUE TITLE
Odd Animation Interrupt Behavior

### ISSUE THREAD

**Issue by amccloud** [maisano/react-router-transition#6]
React motion appears to be trying to reverse the animation if you go from from `/route/a` to `/route/b` and back to `/route/a` before the animation ends. Because the animation is running in reverse `atEnter` and `atLeave` should also be reversed.

This behavior is noticeable on the demo if you quickly clicks between "another slideLeft" http://maisano.github.io/react-router-transition/demos/#/slideLeft/demo-2?_k=ycnlzx

**Comment by maisano** [comment]
this is because, by design, react-motion supports interrupting animations–in this particular case it's performing correctly because the route re-entering from the opposite direction has not yet unmounted. it's also compounded by the values i used for the spring presets–it fades out more quickly than it translates so it's not entirely apparent that it's still in the process of unmounting.

all this said, it's a goofy side effect that i need to account for.

**Comment by slider82** [comment]
So how to avoid this? Is there a solution?

**Comment by maisano** [comment]
@slider82 there's currently no way to avoid this behavior with the most recently published package on npm. if you want to, you can try the `v4` branch which got rid of this behavior when using `AnimatedSwitch`.
