### ISSUE TITLE
Demo broken in IE11

### ISSUE THREAD

**Issue by ruscal** [maisano/react-router-transition#72]
Just needs a babel-polyfill to cope with array.Find used in getMatchedRoute (AnimatedSwitch.js)

**Comment by jacobangel** [comment]
Hi Ruscal,
Unfortunately, I don't think we want to use a polyfill here, since it's a prototype method. 

I think two fair options would either be:
1. instructing users how to polyfill in their applications in the readme,
2. rewriting the find usage to avoid any requirements of polyfilling at all. 

Would you mind submitting a pull request with the option you think is best? 

Thanks!
